server:
  port: 8080
spring:
  application:
    name: beinet-admin
  profiles:
    active: local
  cloud:
    config:
      profile: ${spring.profiles.active}
      label: test
  servlet:
    multipart:
      max-file-size: 10GB     # 单个文件最大限制
      max-request-size: 10GB  # 整个请求体最大限制
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.72.155:8306/eb-dev?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&socketTimeout=3000&connectTimeout=3000&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=round
    username: root
    password: ENC(eP7nQwcd/E2fjjk8oOG3hyH+4En0uAdF+o1FeDtPe/8BgEK/JfDevg6mgMn6MfWc)
  data:
    redis:
      host: 10.100.72.155
      port: 8379
      password: ENC(eP7nQwcd/E2fjjk8oOG3hyH+4En0uAdF+o1FeDtPe/8BgEK/JfDevg6mgMn6MfWc)
      database: 15            # 数据库索引，注意 0到15

sdk:
  app-key: sdk
  secure-key: ENC(W23usMdaRPEyrbl9IdTAE+t3VuILRJBc1ZeHXKrKjr4dOg1OkdBhVVPaUFaQnpIe)
  # todo: ak/sk可以访问的api列表
  api:
    - /version

jasypt:
  encryptor:
    password: .beinet.cn.

# 文件管理器允许访问的根目录列表
file-manager:
  enabled: true
  dir:
    - d:/mp3
    - D:/initSofts/normal/
    - D:/tmp